[package]
name = "kopy-common-lib"
version = "0.1.0"
authors = ["Ethan Hall <ethan@ehdev.io>"]
edition = "2018"

[dependencies]
log = "0.4"
fern = { version = "0.6", features = ["colored"] }
colored = "1.6"
chrono = "0.4"